/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ReadBookRouteImport } from './routes/read.$book'
import { Route as QuizBookRouteImport } from './routes/quiz.$book'
import { Route as BookBookRouteImport } from './routes/book.$book'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google-callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminQuestionsImportRouteImport } from './routes/admin.questions-import'
import { Route as AdminLanguagesRouteImport } from './routes/admin.languages'
import { Route as AdminBooksRouteImport } from './routes/admin.books'
import { Route as AdminBibleImportRouteImport } from './routes/admin.bible-import'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReadBookRoute = ReadBookRouteImport.update({
  id: '/read/$book',
  path: '/read/$book',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizBookRoute = QuizBookRouteImport.update({
  id: '/quiz/$book',
  path: '/quiz/$book',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookRoute = BookBookRouteImport.update({
  id: '/book/$book',
  path: '/book/$book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google-callback',
  path: '/auth/google-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsImportRoute = AdminQuestionsImportRouteImport.update({
  id: '/questions-import',
  path: '/questions-import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLanguagesRoute = AdminLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBibleImportRoute = AdminBibleImportRouteImport.update({
  id: '/bible-import',
  path: '/bible-import',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/bible-import': typeof AdminBibleImportRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/questions-import': typeof AdminQuestionsImportRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/book/$book': typeof BookBookRoute
  '/quiz/$book': typeof QuizBookRoute
  '/read/$book': typeof ReadBookRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/admin/bible-import': typeof AdminBibleImportRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/questions-import': typeof AdminQuestionsImportRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/book/$book': typeof BookBookRoute
  '/quiz/$book': typeof QuizBookRoute
  '/read/$book': typeof ReadBookRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/bible-import': typeof AdminBibleImportRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/questions-import': typeof AdminQuestionsImportRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/book/$book': typeof BookBookRoute
  '/quiz/$book': typeof QuizBookRoute
  '/read/$book': typeof ReadBookRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/admin/bible-import'
    | '/admin/books'
    | '/admin/languages'
    | '/admin/questions-import'
    | '/admin/users'
    | '/auth/google-callback'
    | '/book/$book'
    | '/quiz/$book'
    | '/read/$book'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/admin/bible-import'
    | '/admin/books'
    | '/admin/languages'
    | '/admin/questions-import'
    | '/admin/users'
    | '/auth/google-callback'
    | '/book/$book'
    | '/quiz/$book'
    | '/read/$book'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/admin/bible-import'
    | '/admin/books'
    | '/admin/languages'
    | '/admin/questions-import'
    | '/admin/users'
    | '/auth/google-callback'
    | '/book/$book'
    | '/quiz/$book'
    | '/read/$book'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  BookBookRoute: typeof BookBookRoute
  QuizBookRoute: typeof QuizBookRoute
  ReadBookRoute: typeof ReadBookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/read/$book': {
      id: '/read/$book'
      path: '/read/$book'
      fullPath: '/read/$book'
      preLoaderRoute: typeof ReadBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$book': {
      id: '/quiz/$book'
      path: '/quiz/$book'
      fullPath: '/quiz/$book'
      preLoaderRoute: typeof QuizBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$book': {
      id: '/book/$book'
      path: '/book/$book'
      fullPath: '/book/$book'
      preLoaderRoute: typeof BookBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google-callback': {
      id: '/auth/google-callback'
      path: '/auth/google-callback'
      fullPath: '/auth/google-callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions-import': {
      id: '/admin/questions-import'
      path: '/questions-import'
      fullPath: '/admin/questions-import'
      preLoaderRoute: typeof AdminQuestionsImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/languages': {
      id: '/admin/languages'
      path: '/languages'
      fullPath: '/admin/languages'
      preLoaderRoute: typeof AdminLanguagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bible-import': {
      id: '/admin/bible-import'
      path: '/bible-import'
      fullPath: '/admin/bible-import'
      preLoaderRoute: typeof AdminBibleImportRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBibleImportRoute: typeof AdminBibleImportRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminLanguagesRoute: typeof AdminLanguagesRoute
  AdminQuestionsImportRoute: typeof AdminQuestionsImportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBibleImportRoute: AdminBibleImportRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminLanguagesRoute: AdminLanguagesRoute,
  AdminQuestionsImportRoute: AdminQuestionsImportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  BookBookRoute: BookBookRoute,
  QuizBookRoute: QuizBookRoute,
  ReadBookRoute: ReadBookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
